In [206]:
import pandas as pd
import numpy as np
training_data= np.genfromtxt("train.csv", delimiter=",")
testing_data = np.genfromtxt("test.csv", delimiter=",")
training_data.shape

(379, 14)

In [207]:
training_data

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011, 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412, 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588, 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299, 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218, 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335, 50.        ]])

In [208]:
from sklearn.ensemble import GradientBoostingRegressor
alg=GradientBoostingRegressor()
x=training_data[:,:-1]
y=training_data[:,-1]
alg.fit(x,y)

GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [209]:
normpred=alg.predict(testing_data)                     #prediction using Gradient Descent algo
normpred

array([11.84092569, 26.80499145, 17.09852907, 22.06512279, 21.19058003,
       12.2832724 , 28.78894193, 25.20237061, 18.77275134, 22.99272373,
       23.39058111, 17.6291958 , 19.64676654, 20.87639405, 51.86380438,
       20.4503074 , 23.49131107, 22.87310447, 19.17816831, 30.6365982 ,
       20.89789526, 21.49588187, 36.62299579, 31.39775722, 33.44746403,
       16.38574194, 20.47642029, 30.64770333, 19.97381035, 28.7847961 ,
       17.218498  , 24.68879147, 20.79190642, 22.83448526,  8.58056865,
       23.80896034, 22.57697789, 20.44057093, 22.71189925,  8.0482711 ,
       15.14531831, 23.59244202, 24.95488351, 19.90148152, 21.80376912,
        9.42013033, 43.705159  , 24.57774682, 34.28758074, 12.83411894,
       14.06393226, 45.23318763, 14.38762866, 20.95608777, 16.3818815 ,
       19.74580756, 18.88744499, 22.4778254 , 15.32494152, 15.84899874,
       13.68437009, 27.27249687, 22.29881719, 23.0038954 , 14.49435547,
       16.20543174, 32.88520177, 12.57183546, 20.91664926, 21.38

In [210]:
def gd(training_data,learning_rate,number_of_iteration,n):
    m=[0 for i in range(n)]
    c=0
    for i in range(number_of_iteration):
        m,c=step_gradient(training_data,learning_rate,m,c,n)
        cost(training_data,m,c)
    return m,c

In [211]:
def step_gradient(training_data,learning_rate,m,c,n):
    m_slope=[0 for i in range(n)]
    c_slope=0
    M=len(training_data)
    for t in range(n):
        for i in range(M):
            x=training_data[i,0:-1]
            y=training_data[i,-1]
            val=0
            for j in range(len(x)):
                val+=m[j]*x[j]
            m_slope[t]+=(-2/M)*((y-val-c)*x[t])
            c_slope+=(-2/M)*(y-val-c)
    for i in range(n):
        m[i]=m[i]-learning_rate*m_slope[i]
    c=c-learning_rate*c_slope
    return m,c

In [216]:
def cost(training_data,m,c):
    total=0
    M=len(training_data)
    for i in range(M):
        x=training_data[i,0:-1]
        y=training_data[i,-1]
        val=0
        for j in range(len(x)):
            val+=m[j]*x[j]
        total+=(1/M)*((y-val-c)**2)
    return total


In [213]:
def run():
    learning_rate=0.0099
    number_of_iteration=500
    m,c=gd(training_data,learning_rate,number_of_iteration,13)
    return m,c

In [220]:
y_pred=[]
def predict(testing_data,m,c,n):
    M=len(testing_data)
    for i in range(M):
        x=testing_data[i,:]
        val=0
        for j in range(n):
            val+=m[j]*x[j]
        ans=val+c
        y_pred.append(ans)


In [221]:
m,c=run()
predict(testing_data,m,c,13)
for i in y_pred:
    print(i)

11.8526035039305
28.819006417016848
22.436693598985045
24.27379105512256
21.07118420525327
2.8368004706157564
29.47791630632109
24.478127846000707
18.841750448806682
23.44320705087561
24.371047424095355
17.94774174827292
18.54446156037926
21.884867068477273
42.68619577795495
24.150742864996342
24.492841301095158
27.69471513994445
20.477880250409275
31.40912150721989
24.189211034981113
24.67394915003638
33.74285997690132
35.93656796350501
32.24805280405832
16.052897717388397
23.079128802326835
33.0377099415402
24.569773261325572
33.4591291351484
17.20533986934923
26.277099418886998
23.53275886456533
25.433544324441478
15.029277720377156
29.390987709860635
26.137178815197256
20.69263748344394
24.112780998338025
9.544666506684786
7.645959337824852
28.686127635894564
29.568176754778925
20.131674098586405
20.356109847758592
2.7765480507188443
39.58313956382923
25.77626149122787
29.950259468250117
16.98836100133172
17.73063233543478
39.98951477981005
17.759056884640838
21.18604820595902
15.8

In [223]:
np.savetxt("bostonpredictions.csv",y_pred,fmt='%f')

In [224]:
from sklearn import preprocessing
scale=preprocessing.StandardScaler()
val1=training_data
scale.fit(val1)
val1=scale.transform(val1)
scaledtrainy=val1[:,-1] # scaled training data output 
scaledtrainy

array([ 1.63059527e+00, -1.28982221e-01, -1.05675944e+00, -2.88943812e-01,
       -1.16770554e-02,  1.07606176e+00,  6.29716867e-02, -1.18318115e-01,
       -2.24959176e-01,  1.14004639e+00,  5.23075807e-02, -2.78279706e-01,
        2.92095210e+00,  2.54925595e-01, -2.56951494e-01, -6.62187522e-01,
       -2.23411614e-02, -2.35623282e-01, -4.48905402e-01,  1.56661063e+00,
        5.23075807e-02,  1.28934388e+00,  1.11871818e+00,  6.49497517e-01,
       -7.47500370e-01, -4.70233614e-01, -5.76874674e-01,  9.48092485e-01,
        4.25551291e-01,  1.58948641e-01, -3.30052674e-02, -3.31600236e-01,
        1.43864136e+00, -5.34218250e-01,  1.15071050e+00, -1.47265958e+00,
       -1.37668262e+00, -9.82110702e-01,  1.83321328e+00,  1.90940959e-01,
       -5.12890038e-01,  1.80276853e-01,  1.48284535e-01,  5.23075807e-02,
       -1.01410302e+00, -6.30195204e-01,  2.03152626e-02,  5.21528245e-01,
       -8.54141430e-01, -9.82110702e-01, -1.23804925e+00, -3.42264342e-01,
       -8.11485006e-01,  